### ISSUE TITLE
Compatibility with React-Toolbox 2

### ISSUE THREAD

**Issue by MorrisGallego** [MaximKomlev/react-toolbox-additions#1]
Hi!

Thanks for your work, sometimes it's necesary to break some specifications in favour of other criteria.

My question is... is this set of components compatible with react-toolbox v2? I mean, the v2 of RT changes a bit (mostly due to the change from SASS to PostCSS).

**Comment by MaximKomlev** [comment]
Actually for now no, I'm going to create branch for such changes and publish beta release until the react-toolbox will support them in official release.

**Comment by MaximKomlev** [comment]
Hi, now you can test new version with postcss supporting. 
Please check the postcss branch.

Thank you!

**Comment by MorrisGallego** [comment]
Sorry for not answering before, I was a bit bussy with other things from job. It works perfectly. Thanks!
